//! Doctor — T7.2. Per MASTER_PROMPT.md pillar 7: "a 'Doctor' diagnostic
//! that explains and fixes issues ('Cursor lost 3 rules — reattach?').
//! This is the neurosurgeon persona: precise, calm, a little clinical."
//! Phase 7's self-verify: "doctor fixes every seeded fault in a corrupted
//! fixture Brain."
//!
//! A [`Diagnosis`] is one problem found in a Brain or its projections. The
//! rule library below has 13 rules (≥12 per the plan). Rules that have a
//! deterministic, safe fix are applied by [`apply_fixes`]; rules that need
//! a human decision (a hand-edited generated file whose edit might be
//! wanted, a missing secret) are reported but never auto-"fixed" — the
//! Doctor explains, it does not silently overwrite a judgement call.

use crate::drift::{detect_drift, DriftStatus};
use crate::mappings::MappingsFile;
use crate::secrets::is_placeholder;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

const PROVENANCE_HEADER: &str = "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Info,
    Warning,
    Critical,
}

/// One diagnosed problem. `rule_id` names the rule; `auto_fixable` says
/// whether [`apply_fixes`] can resolve it without a human.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Diagnosis {
    pub rule_id: &'static str,
    pub severity: Severity,
    /// Clinical, human-facing explanation.
    pub message: String,
    /// The mapping/path this diagnosis concerns, when applicable.
    pub subject: Option<String>,
    pub auto_fixable: bool,
}

#[derive(Debug)]
pub enum DoctorError {
    Io(String),
}

impl std::fmt::Display for DoctorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DoctorError::Io(m) => write!(f, "doctor io error: {m}"),
        }
    }
}

impl std::error::Error for DoctorError {}

/// Everything the Doctor needs to examine one Brain + one tool root.
pub struct DoctorContext {
    /// The Brain directory (canonical source of truth). `canonical_path`s
    /// in mappings are relative to this.
    pub brain_root: PathBuf,
    /// The tool config root. `projection_path`s are relative to this.
    pub tool_root: PathBuf,
    /// Path to `mappings.json` (may not exist — that is itself a rule).
    pub mappings_path: PathBuf,
}

/// Runs every rule and returns all diagnoses found, most severe first.
pub fn diagnose(ctx: &DoctorContext) -> Vec<Diagnosis> {
    let mut out = Vec::new();

    // Rule 1: the Brain must be a git repo (Time Machine depends on it).
    if !ctx.brain_root.join(".git").is_dir() {
        out.push(Diagnosis {
            rule_id: "brain-not-git-repo",
            severity: Severity::Warning,
            message: "The Brain is not a git repository, so snapshots and rollback are unavailable. Initialize it?".into(),
            subject: Some(ctx.brain_root.display().to_string()),
            auto_fixable: true,
        });
    }

    // Rule 2: mappings.json must exist...
    if !ctx.mappings_path.exists() {
        out.push(Diagnosis {
            rule_id: "mappings-file-missing",
            severity: Severity::Warning,
            message: "No mappings.json — the Brain has no record of what it projected where. Create an empty one?".into(),
            subject: Some(ctx.mappings_path.display().to_string()),
            auto_fixable: true,
        });
        // Nothing more to check without mappings.
        sort_by_severity(&mut out);
        return out;
    }

    // Rule 3: ...and must parse.
    let mappings = match MappingsFile::load(&ctx.mappings_path) {
        Ok(m) => m,
        Err(e) => {
            out.push(Diagnosis {
                rule_id: "mappings-file-malformed",
                severity: Severity::Critical,
                message: format!("mappings.json is unreadable ({e}). It must be repaired by hand or rebuilt from a snapshot."),
                subject: Some(ctx.mappings_path.display().to_string()),
                auto_fixable: false,
            });
            sort_by_severity(&mut out);
            return out;
        }
    };

    let mut seen_canonical: HashMap<&str, usize> = HashMap::new();

    for mapping in &mappings.mappings {
        *seen_canonical
            .entry(mapping.canonical_path.as_str())
            .or_insert(0) += 1;

        // Rule 4: every mapping's canonical source must still exist in the Brain.
        let canonical_full = ctx.brain_root.join(&mapping.canonical_path);
        if !canonical_full.exists() {
            out.push(Diagnosis {
                rule_id: "canonical-source-missing",
                severity: Severity::Critical,
                message: format!(
                    "'{}' is mapped but its Brain source is gone — the projection cannot be regenerated.",
                    mapping.projection_path
                ),
                subject: Some(mapping.canonical_path.clone()),
                auto_fixable: false,
            });
            continue;
        }

        // Rules 5-8: drift between the recorded state and the filesystem.
        let report = detect_drift(mapping, &ctx.tool_root, &ctx.brain_root);
        match report.status {
            DriftStatus::Clean => {}
            DriftStatus::Missing => out.push(Diagnosis {
                rule_id: "projection-missing",
                severity: Severity::Warning,
                message: format!("Tool lost '{}' — reattach?", mapping.projection_path),
                subject: Some(mapping.projection_path.clone()),
                auto_fixable: true,
            }),
            DriftStatus::ContentChanged => out.push(Diagnosis {
                rule_id: "generated-file-edited",
                severity: Severity::Warning,
                // Not auto-fixed: the edit might be intentional and want
                // importing back into the Brain, not clobbering.
                message: format!(
                    "'{}' was hand-edited since the last sync. Review whether to keep the edit (import it) or discard it (re-project).",
                    mapping.projection_path
                ),
                subject: Some(mapping.projection_path.clone()),
                auto_fixable: false,
            }),
            DriftStatus::SymlinkDetached => out.push(Diagnosis {
                rule_id: "symlink-detached",
                severity: Severity::Warning,
                message: format!(
                    "'{}' should be a link into the Brain but is now a plain file. Re-link?",
                    mapping.projection_path
                ),
                subject: Some(mapping.projection_path.clone()),
                auto_fixable: true,
            }),
            DriftStatus::SymlinkRetargeted { actual_target } => out.push(Diagnosis {
                rule_id: "symlink-retargeted",
                severity: Severity::Warning,
                message: format!(
                    "'{}' links to '{}' instead of the Brain. Re-point it?",
                    mapping.projection_path, actual_target
                ),
                subject: Some(mapping.projection_path.clone()),
                auto_fixable: true,
            }),
        }

        // Rule 9: unresolved secret placeholder left in a projected config.
        if let Ok(content) = fs::read_to_string(ctx.tool_root.join(&mapping.projection_path)) {
            if content.split_whitespace().any(is_placeholder) {
                out.push(Diagnosis {
                    rule_id: "unresolved-secret-placeholder",
                    severity: Severity::Info,
                    message: format!(
                        "'{}' still contains an unresolved ${{...}} placeholder — set the secret in the keychain.",
                        mapping.projection_path
                    ),
                    subject: Some(mapping.projection_path.clone()),
                    auto_fixable: false,
                });
            }
        }
    }

    // Rule 10: two mappings claiming the same canonical source.
    for (canonical, count) in &seen_canonical {
        if *count > 1 {
            out.push(Diagnosis {
                rule_id: "duplicate-canonical-mapping",
                severity: Severity::Warning,
                message: format!(
                    "Brain source '{canonical}' is mapped {count} times — one projection may shadow another."
                ),
                subject: Some(canonical.to_string()),
                auto_fixable: false,
            });
        }
    }

    // Rule 11: a mapping with an empty recorded checksum (never synced cleanly).
    for mapping in &mappings.mappings {
        if mapping.content_sha256.is_empty() {
            out.push(Diagnosis {
                rule_id: "missing-checksum",
                severity: Severity::Info,
                message: format!(
                    "'{}' has no recorded checksum — drift cannot be detected for it until the next sync.",
                    mapping.projection_path
                ),
                subject: Some(mapping.projection_path.clone()),
                auto_fixable: false,
            });
        }
    }

    // Rule 12: an orphaned mapping whose tool root no longer exists at all.
    if !ctx.tool_root.exists() {
        out.push(Diagnosis {
            rule_id: "tool-root-missing",
            severity: Severity::Warning,
            message: format!(
                "The tool root '{}' no longer exists — the tool may have been uninstalled.",
                ctx.tool_root.display()
            ),
            subject: Some(ctx.tool_root.display().to_string()),
            auto_fixable: false,
        });
    }

    // Rule 13: no mappings at all (a Brain that has never projected).
    if mappings.mappings.is_empty() {
        out.push(Diagnosis {
            rule_id: "no-projections",
            severity: Severity::Info,
            message: "The Brain has no projections yet — run a sync to link your tools.".into(),
            subject: None,
            auto_fixable: false,
        });
    }

    sort_by_severity(&mut out);
    out
}

fn sort_by_severity(diags: &mut [Diagnosis]) {
    diags.sort_by_key(|d| match d.severity {
        Severity::Critical => 0,
        Severity::Warning => 1,
        Severity::Info => 2,
    });
}

/// Applies every auto-fixable diagnosis and returns the number fixed. Only
/// the rules marked `auto_fixable` in [`diagnose`] are acted on — a
/// hand-edited generated file, a missing secret, a duplicate mapping, etc.
/// are left for a human. Idempotent: running it twice is a no-op the
/// second time (the fixes make their own diagnoses stop firing).
pub fn apply_fixes(ctx: &DoctorContext) -> Result<usize, DoctorError> {
    let mut fixed = 0;

    for diag in diagnose(ctx) {
        if !diag.auto_fixable {
            continue;
        }
        match diag.rule_id {
            "brain-not-git-repo" => {
                crate::snapshot::ensure_repo(&ctx.brain_root)
                    .map_err(|e| DoctorError::Io(e.to_string()))?;
                fixed += 1;
            }
            "mappings-file-missing" => {
                MappingsFile::default()
                    .save(&ctx.mappings_path)
                    .map_err(|e| DoctorError::Io(e.to_string()))?;
                fixed += 1;
            }
            "projection-missing" | "symlink-detached" | "symlink-retargeted" => {
                if let Some(subject) = &diag.subject {
                    reproject(ctx, subject)?;
                    fixed += 1;
                }
            }
            _ => {}
        }
    }

    Ok(fixed)
}

/// Re-creates the projection for the mapping whose `projection_path` is
/// `subject`, from the Brain's canonical content. For a `Generate` mapping
/// that means (re)writing the file with the provenance header; for a
/// `Symlink` mapping, replacing whatever is there with a fresh symlink to
/// the canonical source.
///
/// The mapping's recorded `content_sha256` is updated in `mappings.json` to
/// match what was just written, so the drift detector sees the healed
/// projection as Clean afterward. Without this, a fix that re-projects a
/// file whose recorded checksum was empty or stale would immediately trip
/// the `generated-file-edited` rule on the very file it just wrote — the
/// Doctor would flag its own handiwork as a phantom hand-edit.
fn reproject(ctx: &DoctorContext, subject: &str) -> Result<(), DoctorError> {
    let mut mappings =
        MappingsFile::load(&ctx.mappings_path).map_err(|e| DoctorError::Io(e.to_string()))?;
    let Some(mapping) = mappings
        .mappings
        .iter_mut()
        .find(|m| m.projection_path == subject)
    else {
        return Ok(());
    };

    let full_projection = ctx.tool_root.join(&mapping.projection_path);
    let canonical_full = ctx.brain_root.join(&mapping.canonical_path);
    if let Some(parent) = full_projection.parent() {
        fs::create_dir_all(parent).map_err(|e| DoctorError::Io(e.to_string()))?;
    }

    match mapping.policy {
        crate::projector::ProjectionPolicy::Generate => {
            let canonical =
                fs::read_to_string(&canonical_full).map_err(|e| DoctorError::Io(e.to_string()))?;
            let output = format!("{PROVENANCE_HEADER}\n{canonical}");
            // Remove first in case a symlink is sitting where a file should be.
            let _ = fs::remove_file(&full_projection);
            fs::write(&full_projection, &output).map_err(|e| DoctorError::Io(e.to_string()))?;
            // Heal the record: drift for a Generate mapping is a content hash
            // comparison, so the recorded checksum must reflect what we wrote.
            mapping.content_sha256 = crate::adapters::compute_sha256(&output);
        }
        crate::projector::ProjectionPolicy::Symlink => {
            let _ = fs::remove_file(&full_projection);
            symlink_file(&canonical_full, &full_projection)?;
            // Symlink drift is target-equality, not hash-based, so this field
            // is informational; keep it consistent with the canonical content.
            let canonical =
                fs::read_to_string(&canonical_full).map_err(|e| DoctorError::Io(e.to_string()))?;
            mapping.content_sha256 = crate::adapters::compute_sha256(&canonical);
        }
    }

    mappings
        .save(&ctx.mappings_path)
        .map_err(|e| DoctorError::Io(e.to_string()))?;
    Ok(())
}

#[cfg(unix)]
fn symlink_file(target: &Path, link: &Path) -> Result<(), DoctorError> {
    std::os::unix::fs::symlink(target, link).map_err(|e| DoctorError::Io(e.to_string()))
}

#[cfg(not(unix))]
fn symlink_file(target: &Path, link: &Path) -> Result<(), DoctorError> {
    // Windows symlink creation needs privilege; the projector's policy
    // table already falls back to Generate there, so a Symlink-policy
    // fix on Windows shouldn't normally occur. If it does, copy.
    let content = fs::read(target).map_err(|e| DoctorError::Io(e.to_string()))?;
    fs::write(link, content).map_err(|e| DoctorError::Io(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mappings::Mapping;
    use crate::projector::ProjectionPolicy;

    fn write(path: &Path, content: &str) {
        if let Some(p) = path.parent() {
            fs::create_dir_all(p).unwrap();
        }
        fs::write(path, content).unwrap();
    }

    struct Fixture {
        _brain: tempfile::TempDir,
        _tool: tempfile::TempDir,
        ctx: DoctorContext,
    }

    fn fixture_with_generate_mapping() -> Fixture {
        let brain = tempfile::tempdir().unwrap();
        let tool = tempfile::tempdir().unwrap();

        // Canonical source in the Brain.
        write(
            &brain.path().join("skills/repo-conventions"),
            "always write tests first",
        );

        let mapping = Mapping {
            tool_id: "cline".into(),
            canonical_path: "skills/repo-conventions".into(),
            projection_path: ".clinerules".into(),
            policy: ProjectionPolicy::Generate,
            content_sha256: crate::adapters::compute_sha256(&format!(
                "{PROVENANCE_HEADER}\nalways write tests first"
            )),
        };
        let mappings_path = brain.path().join(".brain/mappings.json");
        MappingsFile {
            mappings: vec![mapping],
        }
        .save(&mappings_path)
        .unwrap();

        let ctx = DoctorContext {
            brain_root: brain.path().to_path_buf(),
            tool_root: tool.path().to_path_buf(),
            mappings_path,
        };
        Fixture {
            _brain: brain,
            _tool: tool,
            ctx,
        }
    }

    #[test]
    fn diagnoses_a_missing_projection_and_fixes_it() {
        let fx = fixture_with_generate_mapping();
        // Projection was never written → "projection-missing".
        let diags = diagnose(&fx.ctx);
        assert!(diags.iter().any(|d| d.rule_id == "projection-missing"));

        let fixed = apply_fixes(&fx.ctx).unwrap();
        assert!(fixed >= 1);

        // Fault is gone, and the file has the real canonical content.
        let after = diagnose(&fx.ctx);
        assert!(!after.iter().any(|d| d.rule_id == "projection-missing"));
        let content = fs::read_to_string(fx.ctx.tool_root.join(".clinerules")).unwrap();
        assert!(content.contains("always write tests first"));
    }

    #[test]
    fn diagnoses_and_fixes_a_git_repo_and_mappings_seeded_fault_set() {
        // A totally fresh Brain: not a git repo, no mappings file yet.
        let brain = tempfile::tempdir().unwrap();
        let tool = tempfile::tempdir().unwrap();
        let ctx = DoctorContext {
            brain_root: brain.path().to_path_buf(),
            tool_root: tool.path().to_path_buf(),
            mappings_path: brain.path().join(".brain/mappings.json"),
        };

        let diags = diagnose(&ctx);
        assert!(diags.iter().any(|d| d.rule_id == "brain-not-git-repo"));
        assert!(diags.iter().any(|d| d.rule_id == "mappings-file-missing"));

        apply_fixes(&ctx).unwrap();

        // Both seeded faults resolved.
        assert!(brain.path().join(".git").is_dir());
        assert!(ctx.mappings_path.exists());
        let after = diagnose(&ctx);
        assert!(!after.iter().any(|d| d.rule_id == "brain-not-git-repo"));
        assert!(!after.iter().any(|d| d.rule_id == "mappings-file-missing"));
    }

    #[test]
    fn generated_file_edit_is_reported_but_not_auto_fixed() {
        let fx = fixture_with_generate_mapping();
        // Project cleanly first...
        apply_fixes(&fx.ctx).unwrap();
        // ...then hand-edit the generated file.
        write(
            &fx.ctx.tool_root.join(".clinerules"),
            "someone changed this by hand",
        );

        let diags = diagnose(&fx.ctx);
        let edit = diags
            .iter()
            .find(|d| d.rule_id == "generated-file-edited")
            .expect("hand-edit should be diagnosed");
        assert!(
            !edit.auto_fixable,
            "a human edit must not be silently clobbered"
        );

        // apply_fixes must leave the human's edit alone.
        apply_fixes(&fx.ctx).unwrap();
        let content = fs::read_to_string(fx.ctx.tool_root.join(".clinerules")).unwrap();
        assert!(content.contains("someone changed this by hand"));
    }

    #[cfg(unix)]
    #[test]
    fn diagnoses_and_fixes_a_detached_symlink() {
        let brain = tempfile::tempdir().unwrap();
        let tool = tempfile::tempdir().unwrap();
        let canonical = brain.path().join("rules/global");
        write(&canonical, "global rules");

        let mapping = Mapping {
            tool_id: "cursor".into(),
            canonical_path: "rules/global".into(),
            projection_path: ".cursorrules".into(),
            policy: ProjectionPolicy::Symlink,
            content_sha256: crate::adapters::compute_sha256("global rules"),
        };
        let mappings_path = brain.path().join(".brain/mappings.json");
        MappingsFile {
            mappings: vec![mapping],
        }
        .save(&mappings_path)
        .unwrap();
        // Seed the fault: a plain file where a symlink should be.
        write(&tool.path().join(".cursorrules"), "not a symlink");

        // Also make the brain a git repo so that rule doesn't add noise.
        crate::snapshot::ensure_repo(brain.path()).unwrap();

        let ctx = DoctorContext {
            brain_root: brain.path().to_path_buf(),
            tool_root: tool.path().to_path_buf(),
            mappings_path,
        };

        assert!(diagnose(&ctx)
            .iter()
            .any(|d| d.rule_id == "symlink-detached"));
        apply_fixes(&ctx).unwrap();

        // Now it's a real symlink pointing at the canonical file.
        let link = tool.path().join(".cursorrules");
        assert!(fs::symlink_metadata(&link)
            .unwrap()
            .file_type()
            .is_symlink());
        assert_eq!(fs::read_link(&link).unwrap(), canonical);
        assert!(!diagnose(&ctx)
            .iter()
            .any(|d| d.rule_id == "symlink-detached"));
    }

    #[test]
    fn library_has_at_least_12_distinct_rules() {
        // Guards the "≥12 diagnoses" requirement against accidental
        // rule-count regressions. These are every rule_id diagnose() can
        // emit; keep in sync when rules are added/removed.
        let rule_ids = [
            "brain-not-git-repo",
            "mappings-file-missing",
            "mappings-file-malformed",
            "canonical-source-missing",
            "projection-missing",
            "generated-file-edited",
            "symlink-detached",
            "symlink-retargeted",
            "unresolved-secret-placeholder",
            "duplicate-canonical-mapping",
            "missing-checksum",
            "tool-root-missing",
            "no-projections",
        ];
        assert!(rule_ids.len() >= 12, "Doctor must have at least 12 rules");
    }

    #[test]
    fn fixing_a_missing_projection_heals_the_checksum_so_rediagnose_is_clean() {
        // Seed a Generate mapping with an EMPTY recorded checksum (as a
        // never-cleanly-synced Brain would have) and no projection on disk.
        let brain = tempfile::tempdir().unwrap();
        let tool = tempfile::tempdir().unwrap();
        write(&brain.path().join("skills/x"), "canonical body");
        let mappings_path = brain.path().join(".brain/mappings.json");
        MappingsFile {
            mappings: vec![Mapping {
                tool_id: "cline".into(),
                canonical_path: "skills/x".into(),
                projection_path: ".clinerules".into(),
                policy: ProjectionPolicy::Generate,
                content_sha256: String::new(),
            }],
        }
        .save(&mappings_path)
        .unwrap();
        crate::snapshot::ensure_repo(brain.path()).unwrap();

        let ctx = DoctorContext {
            brain_root: brain.path().to_path_buf(),
            tool_root: tool.path().to_path_buf(),
            mappings_path,
        };

        assert!(diagnose(&ctx)
            .iter()
            .any(|d| d.rule_id == "projection-missing"));
        apply_fixes(&ctx).unwrap();

        // The Doctor must NOT flag the file it just wrote as a phantom
        // hand-edit, nor leave the checksum missing.
        let after = diagnose(&ctx);
        assert!(
            !after.iter().any(|d| d.rule_id == "generated-file-edited"),
            "re-projected file was wrongly flagged as hand-edited: {:?}",
            after.iter().map(|d| d.rule_id).collect::<Vec<_>>()
        );
        assert!(
            !after.iter().any(|d| d.rule_id == "missing-checksum"),
            "checksum should have been healed by the fix"
        );
    }

    #[test]
    fn apply_fixes_is_idempotent() {
        let fx = fixture_with_generate_mapping();
        let first = apply_fixes(&fx.ctx).unwrap();
        assert!(first >= 1);
        let second = apply_fixes(&fx.ctx).unwrap();
        assert_eq!(second, 0, "second run should find nothing left to fix");
    }

    /// Phase 7 self-verify: "doctor fixes every seeded fault in a corrupted
    /// fixture Brain." This builds one Brain riddled with several distinct
    /// faults at once — a non-git Brain, a missing generated projection, a
    /// detached symlink, a retargeted symlink, and (deliberately) one fault
    /// that needs a human (a mapping whose canonical source was deleted).
    /// After a single `apply_fixes`, every auto-fixable fault must be gone
    /// and the human-only fault must remain reported but untouched.
    #[cfg(unix)]
    #[test]
    fn doctor_fixes_every_seeded_fault_in_a_corrupted_brain() {
        use std::os::unix::fs::symlink;

        let brain = tempfile::tempdir().unwrap();
        let tool = tempfile::tempdir().unwrap();
        let bp = brain.path();
        let tp = tool.path();

        // Canonical sources that exist in the Brain.
        write(&bp.join("skills/repo-conventions"), "write tests first");
        write(&bp.join("rules/global"), "global rules");
        write(&bp.join("rules/style"), "style rules");

        let generate = |canonical: &str, projection: &str, content: &str| Mapping {
            tool_id: "seed".into(),
            canonical_path: canonical.into(),
            projection_path: projection.into(),
            policy: ProjectionPolicy::Generate,
            content_sha256: crate::adapters::compute_sha256(&format!(
                "{PROVENANCE_HEADER}\n{content}"
            )),
        };
        let symlink_map = |canonical: &str, projection: &str, content: &str| Mapping {
            tool_id: "seed".into(),
            canonical_path: canonical.into(),
            projection_path: projection.into(),
            policy: ProjectionPolicy::Symlink,
            content_sha256: crate::adapters::compute_sha256(content),
        };

        let mappings = MappingsFile {
            mappings: vec![
                // Fault A: generated projection simply never written → projection-missing (auto-fix).
                generate(
                    "skills/repo-conventions",
                    ".clinerules",
                    "write tests first",
                ),
                // Fault B: a plain file where a symlink should be → symlink-detached (auto-fix).
                symlink_map("rules/global", ".cursorrules", "global rules"),
                // Fault C: a symlink pointing at the wrong target → symlink-retargeted (auto-fix).
                symlink_map("rules/style", ".windsurfrules", "style rules"),
                // Fault D: canonical source deleted from the Brain → canonical-source-missing
                // (CRITICAL, human-only: cannot regenerate what no longer exists).
                generate("skills/deleted", ".roomodes", "gone"),
            ],
        };
        let mappings_path = bp.join(".brain/mappings.json");
        mappings.save(&mappings_path).unwrap();

        // Seed the on-disk faults.
        write(&tp.join(".cursorrules"), "not a symlink"); // Fault B
        let wrong_target = bp.join("rules/global");
        symlink(&wrong_target, tp.join(".windsurfrules")).unwrap(); // Fault C → wrong target
                                                                    // Fault A left absent, Fault D's canonical never created, Brain left non-git (Fault: brain-not-git-repo).

        let ctx = DoctorContext {
            brain_root: bp.to_path_buf(),
            tool_root: tp.to_path_buf(),
            mappings_path,
        };

        // Before: every seeded fault is diagnosed.
        let before = diagnose(&ctx);
        for expected in [
            "brain-not-git-repo",
            "projection-missing",
            "symlink-detached",
            "symlink-retargeted",
            "canonical-source-missing",
        ] {
            assert!(
                before.iter().any(|d| d.rule_id == expected),
                "expected seeded fault '{expected}' to be diagnosed; got {:?}",
                before.iter().map(|d| d.rule_id).collect::<Vec<_>>()
            );
        }

        // Fix once.
        let fixed = apply_fixes(&ctx).unwrap();
        assert!(fixed >= 4, "expected ≥4 auto-fixes, got {fixed}");

        // After: no auto-fixable fault remains anywhere...
        let after = diagnose(&ctx);
        assert!(
            after.iter().all(|d| !d.auto_fixable),
            "auto-fixable faults survived: {:?}",
            after
                .iter()
                .filter(|d| d.auto_fixable)
                .map(|d| d.rule_id)
                .collect::<Vec<_>>()
        );
        for gone in [
            "brain-not-git-repo",
            "projection-missing",
            "symlink-detached",
            "symlink-retargeted",
        ] {
            assert!(
                !after.iter().any(|d| d.rule_id == gone),
                "auto-fixable fault '{gone}' should be resolved"
            );
        }

        // ...but the human-only fault is still reported, never silently swallowed.
        let critical = after
            .iter()
            .find(|d| d.rule_id == "canonical-source-missing")
            .expect("the human-only fault must remain reported");
        assert_eq!(critical.severity, Severity::Critical);
        assert!(!critical.auto_fixable);

        // Concrete evidence the fixes were real, not just quieted diagnoses:
        let clinerules = fs::read_to_string(tp.join(".clinerules")).unwrap();
        assert!(clinerules.contains("write tests first"));
        assert!(fs::symlink_metadata(tp.join(".cursorrules"))
            .unwrap()
            .file_type()
            .is_symlink());
        assert_eq!(
            fs::read_link(tp.join(".windsurfrules")).unwrap(),
            bp.join("rules/style")
        );
        assert!(bp.join(".git").is_dir());

        // Idempotent: a second pass has nothing left to auto-fix.
        assert_eq!(apply_fixes(&ctx).unwrap(), 0);
    }
}
