//! Projection policy: per MASTER_PROMPT.md §1 pillar 3, symlink where a tool
//! tolerates it, otherwise emit a generated file stamped with provenance.
//! The policy table itself (per-tool, per-OS) is Phase 3 (T3.2); this module
//! defines the two outcomes and the fallback rule shared by every adapter.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectionPolicy {
    /// The tool reads its config through a symlink (or, on Windows, a
    /// directory junction/hardlink) pointed at the Brain.
    Symlink,
    /// The tool cannot tolerate a symlink; write a generated file stamped
    /// `GENERATED BY <brand> — edit in the Brain`.
    Generate,
}

/// Windows without symlink privileges (or any OS where a prior symlink
/// attempt failed) always falls back to `Generate`.
pub fn decide_policy(
    tool_supports_symlink: bool,
    symlink_privilege_available: bool,
) -> ProjectionPolicy {
    if tool_supports_symlink && symlink_privilege_available {
        ProjectionPolicy::Symlink
    } else {
        ProjectionPolicy::Generate
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn falls_back_to_generate_without_symlink_privilege() {
        assert_eq!(decide_policy(true, false), ProjectionPolicy::Generate);
    }

    #[test]
    fn uses_symlink_when_supported_and_privileged() {
        assert_eq!(decide_policy(true, true), ProjectionPolicy::Symlink);
    }
}
