//! Projection policy: per MASTER_PROMPT.md §1 pillar 3, symlink where a tool
//! tolerates it, otherwise emit a generated file stamped with provenance.
//! This module defines the two outcomes, the OS-privilege fallback rule,
//! and the T3.2 per-tool/per-artifact policy table that says which of each
//! adapter's output files the Brain fully owns (safe to symlink) versus
//! which are spliced into a file that also holds unrelated tool/user state
//! (must always be `Generate`, no matter the OS or symlink privilege).

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProjectionPolicy {
    /// The tool reads its config through a symlink (or, on Windows, a
    /// directory junction/hardlink) pointed at the Brain.
    Symlink,
    /// The tool cannot tolerate a symlink; write a generated file stamped
    /// `GENERATED BY <brand> — edit in the Brain`.
    Generate,
}

/// Windows without symlink privileges (or any OS where a prior symlink
/// attempt failed) always falls back to `Generate`.
pub fn decide_policy(
    tool_supports_symlink: bool,
    symlink_privilege_available: bool,
) -> ProjectionPolicy {
    if tool_supports_symlink && symlink_privilege_available {
        ProjectionPolicy::Symlink
    } else {
        ProjectionPolicy::Generate
    }
}

/// The kind of file an adapter writes. Distinguishing these matters because
/// two adapters can write the *same* kind of thing with different
/// ownership: a `Rules` file is always fully Brain-owned, but a
/// `MergedConfig` file (e.g. an MCP settings JSON) is spliced into a file
/// that also holds the user's other, non-Brain settings.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Artifact {
    /// The tool's main memory/rules file (CLAUDE.md, .clinerules, AGENTS.md,
    /// GEMINI.md, .cursorrules, .rules, CONVENTIONS.md, .windsurfrules, the
    /// root copilot-instructions.md) — entirely (re)written by the adapter,
    /// nothing else lives in it.
    Rules,
    /// A per-skill dedicated file (.claude/skills/*/SKILL.md,
    /// .cursor/rules/*.mdc, .continue/rules/*.md, *.instructions.md).
    Skill,
    /// A per-agent dedicated file (.claude/agents/*.md, roo-code's
    /// .roomodes, which is fully regenerated from Brain agents each pass).
    Agent,
    /// A settings/config file the adapter reads, merges Brain-derived keys
    /// into, and writes back — pre-existing unrelated keys must survive the
    /// merge (mcp settings JSON, .aider.conf.yml, .codex/config.toml).
    MergedConfig,
}

/// `(tool_id, artifact, is_dedicated)` — `is_dedicated` is true when the
/// Brain owns the whole file/dir outright (safe to symlink), false when the
/// adapter merges Brain content into a file that also holds unrelated
/// tool/user state (never safe to symlink, regardless of OS or privilege).
/// Derived by reading every adapter's `project()` method in
/// `packages/core/src/adapters/*.rs` — see PROGRESS.md's T3.2 entry.
const POLICY_TABLE: &[(&str, Artifact, bool)] = &[
    ("aider", Artifact::Rules, true),
    ("aider", Artifact::MergedConfig, false),
    ("claude-code", Artifact::Rules, true),
    ("claude-code", Artifact::Skill, true),
    ("claude-code", Artifact::Agent, true),
    ("claude-code", Artifact::MergedConfig, false),
    ("cline", Artifact::Rules, true),
    ("cline", Artifact::MergedConfig, false),
    ("continue", Artifact::Rules, true),
    ("continue", Artifact::MergedConfig, false),
    ("cursor", Artifact::Rules, true),
    ("cursor", Artifact::Skill, true),
    ("gemini-cli", Artifact::Rules, true),
    ("gemini-cli", Artifact::MergedConfig, false),
    ("github-copilot", Artifact::Rules, true),
    ("github-copilot", Artifact::Skill, true),
    ("github-copilot", Artifact::MergedConfig, false),
    ("openai-codex", Artifact::MergedConfig, false),
    ("opencode", Artifact::Rules, true),
    ("roo-code", Artifact::Agent, true),
    ("windsurf", Artifact::Rules, true),
    ("windsurf", Artifact::MergedConfig, false),
    ("zed", Artifact::Rules, true),
    ("zed", Artifact::MergedConfig, false),
];

/// True if `(tool_id, artifact)` is a file/dir the Brain owns outright.
/// Unknown `(tool_id, artifact)` pairs default to `false` — the safe
/// fallback is always `Generate`, never a guessed `Symlink`.
pub fn is_symlink_candidate(tool_id: &str, artifact: Artifact) -> bool {
    POLICY_TABLE
        .iter()
        .find(|(id, art, _)| *id == tool_id && *art == artifact)
        .map(|(_, _, dedicated)| *dedicated)
        .unwrap_or(false)
}

/// The real per-tool policy decision: dedicated artifacts symlink when the
/// caller reports symlink privilege is available on the current OS (see
/// `decide_policy`); merged-config artifacts always generate, since
/// splicing Brain content into a file with unrelated user state can never
/// be represented as a whole-file symlink.
pub fn policy_for(
    tool_id: &str,
    artifact: Artifact,
    symlink_privilege_available: bool,
) -> ProjectionPolicy {
    decide_policy(
        is_symlink_candidate(tool_id, artifact),
        symlink_privilege_available,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::all_adapters;

    #[test]
    fn falls_back_to_generate_without_symlink_privilege() {
        assert_eq!(decide_policy(true, false), ProjectionPolicy::Generate);
    }

    #[test]
    fn uses_symlink_when_supported_and_privileged() {
        assert_eq!(decide_policy(true, true), ProjectionPolicy::Symlink);
    }

    /// Every registered adapter must have at least one POLICY_TABLE row, and
    /// every row's policy must resolve sensibly with and without symlink
    /// privilege (the "per-OS" axis: no privilege is exactly what a Windows
    /// install without Developer Mode/admin looks like).
    #[test]
    fn every_registered_adapter_has_a_policy_row() {
        for adapter in all_adapters() {
            let id = adapter.id();
            let has_row = POLICY_TABLE.iter().any(|(tool_id, _, _)| *tool_id == id);
            assert!(has_row, "adapter '{id}' has no POLICY_TABLE row");
        }
    }

    #[test]
    fn dedicated_rules_files_symlink_when_privileged() {
        for tool_id in ["aider", "claude-code", "cline", "opencode"] {
            assert_eq!(
                policy_for(tool_id, Artifact::Rules, true),
                ProjectionPolicy::Symlink,
                "{tool_id}'s dedicated rules file should symlink when privileged"
            );
            assert_eq!(
                policy_for(tool_id, Artifact::Rules, false),
                ProjectionPolicy::Generate,
                "{tool_id} should fall back to Generate without symlink privilege"
            );
        }
    }

    #[test]
    fn merged_config_files_never_symlink_even_when_privileged() {
        for tool_id in ["cline", "gemini-cli", "openai-codex", "aider", "zed"] {
            assert_eq!(
                policy_for(tool_id, Artifact::MergedConfig, true),
                ProjectionPolicy::Generate,
                "{tool_id}'s merged config splices Brain content into unrelated \
                 user state, so it must never symlink even with privilege"
            );
        }
    }

    #[test]
    fn unknown_tool_artifact_pair_defaults_to_generate() {
        assert!(!is_symlink_candidate("not-a-real-tool", Artifact::Rules));
        assert_eq!(
            policy_for("not-a-real-tool", Artifact::Rules, true),
            ProjectionPolicy::Generate
        );
    }
}
