use super::{clean_jsonc, compute_sha256, strip_provenance};
use crate::adapter::{Adapter, AdapterError, ImportResult, ProjectResult};
use crate::model::{Agent, HealthStatus, McpServer, Skill};
use serde_json::{json, Value};
use std::fs;
use std::path::Path;

pub struct ClineAdapter;

impl Adapter for ClineAdapter {
    fn id(&self) -> &'static str {
        "cline"
    }

    fn detect(&self, root: &Path) -> bool {
        root.join(".clinerules").exists() || root.join("cline_mcp_settings.json").exists()
    }

    fn import(&self, root: &Path) -> Result<ImportResult, AdapterError> {
        let mut skills = Vec::new();
        let mut mcp_servers = Vec::new();

        let rules_path = root.join(".clinerules");
        if rules_path.exists() {
            let raw_content = fs::read_to_string(&rules_path)
                .map_err(|e| AdapterError::Io(format!("Failed to read .clinerules: {}", e)))?;
            let content = strip_provenance(&raw_content);
            let sha256 = compute_sha256(&content);

            skills.push(Skill {
                id: "cline-rules".to_string(),
                version: "1.0.0".to_string(),
                triggers: vec!["*".to_string()],
                targets: vec!["cline".to_string()],
                source: content,
                sha256,
            });
        }

        let mcp_path = root.join("cline_mcp_settings.json");
        if mcp_path.exists() {
            let raw_json = fs::read_to_string(&mcp_path).map_err(|e| {
                AdapterError::Io(format!("Failed to read cline_mcp_settings.json: {}", e))
            })?;
            let cleaned = clean_jsonc(&raw_json);
            let parsed: Value = serde_json::from_str(&cleaned).map_err(|e| {
                AdapterError::Malformed(format!("Invalid JSON in cline_mcp_settings.json: {}", e))
            })?;

            if let Some(mcp_servers_val) = parsed.get("mcpServers").and_then(|v| v.as_object()) {
                for (id, val) in mcp_servers_val {
                    let command = val
                        .get("command")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string();
                    let args: Vec<String> = val
                        .get("args")
                        .and_then(|v| v.as_array())
                        .map(|arr| {
                            arr.iter()
                                .map(|item| item.as_str().unwrap_or("").to_string())
                                .collect()
                        })
                        .unwrap_or_default();

                    let command_or_url = if args.is_empty() {
                        command
                    } else {
                        format!("{} {}", command, args.join(" "))
                    };

                    let mut env_placeholders = Vec::new();
                    if let Some(env_obj) = val.get("env").and_then(|v| v.as_object()) {
                        for key in env_obj.keys() {
                            env_placeholders.push(key.clone());
                        }
                    }
                    env_placeholders.sort(); // Deterministic ordering

                    mcp_servers.push(McpServer {
                        id: id.clone(),
                        transport: "stdio".to_string(),
                        command_or_url,
                        env_placeholders,
                        targets: vec!["cline".to_string()],
                        health: HealthStatus::Unknown,
                    });
                }
            }
        }

        Ok(ImportResult {
            skills,
            agents: Vec::new(),
            mcp_servers,
        })
    }

    fn project(
        &self,
        root: &Path,
        skills: &[Skill],
        _agents: &[Agent],
        mcp_servers: &[McpServer],
    ) -> Result<ProjectResult, AdapterError> {
        let mut written = Vec::new();

        // 1. Project Skills
        let cline_skills: Vec<&Skill> = skills
            .iter()
            .filter(|s| s.targets.contains(&"cline".to_string()))
            .collect();

        if !cline_skills.is_empty() {
            let concatenated: String = cline_skills
                .iter()
                .map(|s| s.source.as_str())
                .collect::<Vec<&str>>()
                .join("\n\n---\n\n");
            let output = format!(
                "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->\n{}",
                concatenated
            );
            let rules_path = root.join(".clinerules");
            fs::write(&rules_path, output)
                .map_err(|e| AdapterError::Io(format!("Failed to write .clinerules: {}", e)))?;
            written.push(".clinerules".to_string());
        }

        // 2. Project MCP Servers
        let cline_servers: Vec<&McpServer> = mcp_servers
            .iter()
            .filter(|s| s.targets.contains(&"cline".to_string()))
            .collect();

        if !cline_servers.is_empty() {
            let mcp_path = root.join("cline_mcp_settings.json");
            let mut current_json = if mcp_path.exists() {
                let raw_json = fs::read_to_string(&mcp_path).map_err(|e| {
                    AdapterError::Io(format!("Failed to read cline_mcp_settings.json: {}", e))
                })?;
                let cleaned = clean_jsonc(&raw_json);
                serde_json::from_str(&cleaned).unwrap_or_else(|_| json!({ "mcpServers": {} }))
            } else {
                json!({ "mcpServers": {} })
            };

            if !current_json.is_object() {
                current_json = json!({ "mcpServers": {} });
            }

            let mcp_servers_map = current_json
                .as_object_mut()
                .unwrap()
                .entry("mcpServers")
                .or_insert_with(|| json!({}))
                .as_object_mut()
                .ok_or_else(|| {
                    AdapterError::Malformed("mcpServers is not an object".to_string())
                })?;

            for server in cline_servers {
                let parts: Vec<&str> = server.command_or_url.split_whitespace().collect();
                if parts.is_empty() {
                    continue;
                }
                let command = parts[0].to_string();
                let args: Vec<Value> = parts[1..]
                    .iter()
                    .map(|s| Value::String(s.to_string()))
                    .collect();

                // Build env preserving any existing variables
                let mut env_obj = serde_json::Map::new();
                if let Some(existing_server) = mcp_servers_map.get(&server.id) {
                    if let Some(existing_env) =
                        existing_server.get("env").and_then(|v| v.as_object())
                    {
                        env_obj = existing_env.clone();
                    }
                }

                for key in &server.env_placeholders {
                    if !env_obj.contains_key(key) {
                        env_obj.insert(key.clone(), Value::String("".to_string()));
                    }
                }

                let new_server = json!({
                    "command": command,
                    "args": args,
                    "env": env_obj
                });

                mcp_servers_map.insert(server.id.clone(), new_server);
            }

            let pretty = serde_json::to_string_pretty(&current_json)
                .map_err(|e| AdapterError::Malformed(format!("Failed to serialize JSON: {}", e)))?;
            fs::write(&mcp_path, pretty).map_err(|e| {
                AdapterError::Io(format!("Failed to write cline_mcp_settings.json: {}", e))
            })?;
            written.push("cline_mcp_settings.json".to_string());
        }

        Ok(ProjectResult {
            written,
            symlinked: Vec::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_cline_detect() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;
        assert!(!adapter.detect(dir.path()));

        fs::write(dir.path().join(".clinerules"), "test").unwrap();
        assert!(adapter.detect(dir.path()));

        let dir2 = tempdir().unwrap();
        fs::write(dir2.path().join("cline_mcp_settings.json"), "{}").unwrap();
        assert!(adapter.detect(dir2.path()));
    }

    #[test]
    fn test_cline_import_export_roundtrip() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;

        let rule_content = "Rule body here";
        fs::write(dir.path().join(".clinerules"), rule_content).unwrap();

        let mcp_content = r#"{
            "mcpServers": {
                "weather": {
                    "command": "node",
                    "args": ["dist/index.js"],
                    "env": {
                        "API_KEY": "secret"
                    }
                }
            }
        }"#;
        fs::write(dir.path().join("cline_mcp_settings.json"), mcp_content).unwrap();

        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills.len(), 1);
        assert_eq!(imported.skills[0].id, "cline-rules");
        assert_eq!(imported.skills[0].source, rule_content);

        assert_eq!(imported.mcp_servers.len(), 1);
        assert_eq!(imported.mcp_servers[0].id, "weather");
        assert_eq!(imported.mcp_servers[0].command_or_url, "node dist/index.js");
        assert_eq!(
            imported.mcp_servers[0].env_placeholders,
            vec!["API_KEY".to_string()]
        );

        // Now project back to a clean directory
        let out_dir = tempdir().unwrap();
        let project_res = adapter
            .project(out_dir.path(), &imported.skills, &[], &imported.mcp_servers)
            .unwrap();

        assert_eq!(project_res.written.len(), 2);
        assert!(project_res.written.contains(&".clinerules".to_string()));
        assert!(project_res
            .written
            .contains(&"cline_mcp_settings.json".to_string()));

        // Check content (with provenance and pretty print)
        let projected_rule = fs::read_to_string(out_dir.path().join(".clinerules")).unwrap();
        assert!(
            projected_rule.contains("<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->")
        );
        assert!(projected_rule.contains(rule_content));

        let projected_mcp =
            fs::read_to_string(out_dir.path().join("cline_mcp_settings.json")).unwrap();
        let parsed: Value = serde_json::from_str(&projected_mcp).unwrap();
        assert_eq!(parsed["mcpServers"]["weather"]["command"], "node");
        assert_eq!(parsed["mcpServers"]["weather"]["args"][0], "dist/index.js");
    }

    #[test]
    fn test_cline_stress_malformed_json() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;

        // Garbled JSON should return Malformed error
        fs::write(
            dir.path().join("cline_mcp_settings.json"),
            "{ invalid json }",
        )
        .unwrap();
        let res = adapter.import(dir.path());
        assert!(matches!(res, Err(AdapterError::Malformed(_))));

        // Empty JSON file is also malformed
        fs::write(dir.path().join("cline_mcp_settings.json"), "").unwrap();
        let res = adapter.import(dir.path());
        assert!(matches!(res, Err(AdapterError::Malformed(_))));
    }

    #[test]
    fn test_cline_stress_empty_rules() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;
        fs::write(dir.path().join(".clinerules"), "").unwrap();
        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills.len(), 1);
        assert_eq!(imported.skills[0].source, "");
    }

    #[test]
    fn test_cline_stress_special_characters() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;
        let special = "🚀 unicode rules! 🦀\n特殊字符\n\t\\\n\"quoted\"";
        fs::write(dir.path().join(".clinerules"), special).unwrap();
        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills.len(), 1);
        assert_eq!(imported.skills[0].source, special);
    }

    #[test]
    fn test_cline_stress_project_malformed_existing_json() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;

        // Existing JSON has mcpServers as a string, not an object
        fs::write(
            dir.path().join("cline_mcp_settings.json"),
            r#"{"mcpServers": "string_not_object"}"#,
        )
        .unwrap();

        let server = McpServer {
            id: "my-server".to_string(),
            transport: "stdio".to_string(),
            command_or_url: "node".to_string(),
            env_placeholders: vec![],
            targets: vec!["cline".to_string()],
            health: HealthStatus::Unknown,
        };

        let res = adapter.project(dir.path(), &[], &[], &[server]);
        // Should return AdapterError::Malformed since mcpServers was not an object and couldn't be merged
        assert!(matches!(res, Err(AdapterError::Malformed(_))));
    }

    #[test]
    fn test_cline_stress_project_invalid_root_json() {
        let dir = tempdir().unwrap();
        let adapter = ClineAdapter;

        // Existing JSON is just a list, not an object
        fs::write(dir.path().join("cline_mcp_settings.json"), r#"[1, 2, 3]"#).unwrap();

        let server = McpServer {
            id: "my-server".to_string(),
            transport: "stdio".to_string(),
            command_or_url: "node".to_string(),
            env_placeholders: vec![],
            targets: vec!["cline".to_string()],
            health: HealthStatus::Unknown,
        };

        let res = adapter.project(dir.path(), &[], &[], &[server]);
        // Since root is not an object, it should overwrite and succeed
        assert!(res.is_ok());
    }
}
