use super::{
    compute_sha256, parse_mdc_frontmatter, safe_join, serialize_mdc_frontmatter, split_frontmatter,
    strip_provenance, MdcFrontmatter,
};
use crate::adapter::{Adapter, AdapterError, ImportResult, ProjectResult};
use crate::model::{Agent, McpServer, Skill};
use std::fs;
use std::path::Path;

pub struct CursorAdapter;

const LEGACY_SKILL_ID: &str = "cursor-legacy-rules";
const RULE_ID_PREFIX: &str = "cursor-rule-";

impl Adapter for CursorAdapter {
    fn id(&self) -> &'static str {
        "cursor"
    }

    fn detect(&self, root: &Path) -> bool {
        root.join(".cursorrules").exists() || root.join(".cursor/rules").is_dir()
    }

    fn import(&self, root: &Path) -> Result<ImportResult, AdapterError> {
        let mut skills = Vec::new();

        let legacy_path = root.join(".cursorrules");
        if legacy_path.exists() {
            let raw = fs::read_to_string(&legacy_path)
                .map_err(|e| AdapterError::Io(format!("Failed to read .cursorrules: {}", e)))?;
            let content = strip_provenance(&raw);
            let sha256 = compute_sha256(&content);
            skills.push(Skill {
                id: LEGACY_SKILL_ID.to_string(),
                version: "1.0.0".to_string(),
                triggers: vec!["*".to_string()],
                targets: vec!["cursor".to_string()],
                source: content,
                sha256,
            });
        }

        let rules_dir = root.join(".cursor/rules");
        if rules_dir.is_dir() {
            let mut entries: Vec<_> = fs::read_dir(&rules_dir)
                .map_err(|e| AdapterError::Io(format!("Failed to read .cursor/rules: {}", e)))?
                .filter_map(|e| e.ok())
                .filter(|e| {
                    // `entry.file_type()` reports the entry itself rather
                    // than following it, unlike `path.is_dir()`; a symlink
                    // planted in a cloned repo (e.g. pointing at ~/.ssh)
                    // must never be read into the Brain — per
                    // MASTER_PROMPT.md's "import never follows symlinks
                    // outside scanned roots".
                    e.file_type().map(|ft| ft.is_file()).unwrap_or(false)
                        && e.path().extension().and_then(|ext| ext.to_str()) == Some("mdc")
                })
                .collect();
            entries.sort_by_key(|e| e.file_name());

            for entry in entries {
                let path = entry.path();
                let stem = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("rule")
                    .to_string();
                let raw = fs::read_to_string(&path).map_err(|e| {
                    AdapterError::Io(format!("Failed to read {}: {}", path.display(), e))
                })?;
                let content = strip_provenance(&raw);
                let (fm_opt, body) = split_frontmatter(&content);
                let fm = fm_opt
                    .map(|fm| parse_mdc_frontmatter(&fm))
                    .unwrap_or_default();

                let triggers = if !fm.globs.is_empty() {
                    fm.globs
                } else if fm.always_apply {
                    vec!["*".to_string()]
                } else {
                    Vec::new()
                };

                let body = body.trim().to_string();
                let sha256 = compute_sha256(&body);
                skills.push(Skill {
                    id: format!("{}{}", RULE_ID_PREFIX, stem),
                    version: "1.0.0".to_string(),
                    triggers,
                    targets: vec!["cursor".to_string()],
                    source: body,
                    sha256,
                });
            }
        }

        Ok(ImportResult {
            skills,
            agents: Vec::new(),
            mcp_servers: Vec::new(),
        })
    }

    fn project(
        &self,
        root: &Path,
        skills: &[Skill],
        _agents: &[Agent],
        _mcp_servers: &[McpServer],
    ) -> Result<ProjectResult, AdapterError> {
        let mut written = Vec::new();

        let cursor_skills: Vec<&Skill> = skills
            .iter()
            .filter(|s| s.targets.contains(&"cursor".to_string()))
            .collect();

        if let Some(legacy) = cursor_skills.iter().find(|s| s.id == LEGACY_SKILL_ID) {
            let output = format!(
                "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->\n{}",
                legacy.source
            );
            fs::write(root.join(".cursorrules"), output)
                .map_err(|e| AdapterError::Io(format!("Failed to write .cursorrules: {}", e)))?;
            written.push(".cursorrules".to_string());
        }

        let rule_skills: Vec<&&Skill> = cursor_skills
            .iter()
            .filter(|s| s.id.starts_with(RULE_ID_PREFIX))
            .collect();

        if !rule_skills.is_empty() {
            let rules_dir = root.join(".cursor/rules");
            fs::create_dir_all(&rules_dir)
                .map_err(|e| AdapterError::Io(format!("Failed to create .cursor/rules: {}", e)))?;

            for skill in rule_skills {
                let slug = &skill.id[RULE_ID_PREFIX.len()..];
                let fm = MdcFrontmatter {
                    globs: skill.triggers.clone(),
                    always_apply: skill.triggers == vec!["*".to_string()],
                };
                let output = format!(
                    "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->\n{}\n\n{}",
                    serialize_mdc_frontmatter(&fm),
                    skill.source
                );
                let rel_path = format!(".cursor/rules/{}.mdc", slug);
                let target_path = safe_join(root, &rel_path)?;
                fs::write(&target_path, output).map_err(|e| {
                    AdapterError::Io(format!("Failed to write {}: {}", rel_path, e))
                })?;
                written.push(rel_path);
            }
        }

        Ok(ProjectResult {
            written,
            symlinked: Vec::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_cursor_project_rejects_path_traversal_in_rule_slug() {
        let dir = tempdir().unwrap();
        let adapter = CursorAdapter;

        // A rule skill id derived from a malicious/malformed upstream
        // config could carry a slug with `..` components; projecting it
        // must not escape the target root.
        let skill = Skill {
            id: format!("{}../../../evil", RULE_ID_PREFIX),
            version: "1.0.0".to_string(),
            triggers: vec!["*.rs".to_string()],
            targets: vec!["cursor".to_string()],
            source: "malicious".to_string(),
            sha256: "hash".to_string(),
        };

        let result = adapter.project(dir.path(), &[skill], &[], &[]);
        assert!(matches!(result, Err(AdapterError::Malformed(_))));
    }

    #[test]
    fn test_cursor_detect() {
        let dir = tempdir().unwrap();
        let adapter = CursorAdapter;
        assert!(!adapter.detect(dir.path()));

        fs::write(dir.path().join(".cursorrules"), "test").unwrap();
        assert!(adapter.detect(dir.path()));

        let dir2 = tempdir().unwrap();
        fs::create_dir_all(dir2.path().join(".cursor/rules")).unwrap();
        assert!(adapter.detect(dir2.path()));
    }

    #[test]
    fn test_cursor_import_export_roundtrip() {
        let dir = tempdir().unwrap();
        let adapter = CursorAdapter;

        fs::write(dir.path().join(".cursorrules"), "Legacy instructions").unwrap();
        fs::create_dir_all(dir.path().join(".cursor/rules")).unwrap();
        fs::write(
            dir.path().join(".cursor/rules/repo-conventions.mdc"),
            "---\ndescription: test rule\nglobs: [\"*.rs\"]\nalwaysApply: false\n---\n\n# Conventions\n\nPrefer editing existing files.",
        ).unwrap();

        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills.len(), 2);

        let legacy = imported
            .skills
            .iter()
            .find(|s| s.id == LEGACY_SKILL_ID)
            .unwrap();
        assert_eq!(legacy.source, "Legacy instructions");

        let rule = imported
            .skills
            .iter()
            .find(|s| s.id == "cursor-rule-repo-conventions")
            .unwrap();
        assert_eq!(rule.triggers, vec!["*.rs".to_string()]);
        assert!(rule.source.contains("Prefer editing existing files."));

        let out_dir = tempdir().unwrap();
        let project_res = adapter
            .project(out_dir.path(), &imported.skills, &[], &[])
            .unwrap();
        assert_eq!(project_res.written.len(), 2);

        let projected_legacy = fs::read_to_string(out_dir.path().join(".cursorrules")).unwrap();
        assert!(projected_legacy.contains("Legacy instructions"));

        let projected_rule =
            fs::read_to_string(out_dir.path().join(".cursor/rules/repo-conventions.mdc")).unwrap();
        assert!(projected_rule.contains("globs: [\"*.rs\"]"));
        assert!(projected_rule.contains("Prefer editing existing files."));
    }

    #[test]
    fn test_cursor_always_apply_rule_becomes_wildcard_trigger() {
        let dir = tempdir().unwrap();
        let adapter = CursorAdapter;
        fs::create_dir_all(dir.path().join(".cursor/rules")).unwrap();
        fs::write(
            dir.path().join(".cursor/rules/global.mdc"),
            "---\nglobs: []\nalwaysApply: true\n---\nAlways-on rule",
        )
        .unwrap();

        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills[0].triggers, vec!["*".to_string()]);
    }

    #[cfg(unix)]
    #[test]
    fn test_cursor_import_does_not_follow_symlinked_rule_files() {
        let dir = tempdir().unwrap();
        let adapter = CursorAdapter;

        let outside = tempdir().unwrap();
        let secret = outside.path().join("secret.mdc");
        fs::write(&secret, "top secret content").unwrap();

        fs::create_dir_all(dir.path().join(".cursor/rules")).unwrap();
        std::os::unix::fs::symlink(&secret, dir.path().join(".cursor/rules/planted.mdc")).unwrap();

        let imported = adapter.import(dir.path()).unwrap();
        assert!(imported.skills.is_empty());
    }

    #[test]
    fn test_cursor_stress_missing_files_graceful() {
        let dir = tempdir().unwrap();
        let adapter = CursorAdapter;
        let imported = adapter.import(dir.path()).unwrap();
        assert!(imported.skills.is_empty());
    }

    /// Imports the golden fixture tree checked into fixtures/cursor/ per
    /// docs/research/cursor.md, so the adapter is validated against a
    /// real-shaped config, not just tempdir-constructed strings.
    #[test]
    fn test_cursor_imports_golden_fixture() {
        let fixture_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/cursor");
        let adapter = CursorAdapter;
        assert!(adapter.detect(&fixture_root));

        let imported = adapter.import(&fixture_root).unwrap();
        assert_eq!(imported.skills.len(), 2);
        assert!(imported.skills.iter().any(|s| s.id == LEGACY_SKILL_ID));
        let rule = imported
            .skills
            .iter()
            .find(|s| s.id == "cursor-rule-repo-conventions")
            .unwrap();
        assert_eq!(rule.triggers, vec!["*.rs".to_string()]);
        assert!(rule.source.contains("Repo Conventions"));
    }
}
