use super::{compute_sha256, strip_provenance};
use crate::adapter::{Adapter, AdapterError, ImportResult, ProjectResult};
use crate::model::{Agent, HealthStatus, McpServer, Skill};
use serde_json::{json, Value};
use std::fs;
use std::path::Path;

pub struct GeminiCliAdapter;

impl Adapter for GeminiCliAdapter {
    fn id(&self) -> &'static str {
        "gemini-cli"
    }

    fn detect(&self, root: &Path) -> bool {
        root.join("GEMINI.md").exists() || root.join(".gemini/settings.json").exists()
    }

    fn import(&self, root: &Path) -> Result<ImportResult, AdapterError> {
        let mut skills = Vec::new();
        let mut mcp_servers = Vec::new();

        let memory_path = root.join("GEMINI.md");
        if memory_path.exists() {
            let raw = fs::read_to_string(&memory_path)
                .map_err(|e| AdapterError::Io(format!("Failed to read GEMINI.md: {}", e)))?;
            let content = strip_provenance(&raw);
            let sha256 = compute_sha256(&content);
            skills.push(Skill {
                id: "gemini-cli-memory".to_string(),
                version: "1.0.0".to_string(),
                triggers: vec!["*".to_string()],
                targets: vec!["gemini-cli".to_string()],
                source: content,
                sha256,
            });
        }

        let settings_path = root.join(".gemini/settings.json");
        if settings_path.exists() {
            let raw_json = fs::read_to_string(&settings_path).map_err(|e| {
                AdapterError::Io(format!("Failed to read .gemini/settings.json: {}", e))
            })?;
            let parsed: Value = serde_json::from_str(&raw_json).map_err(|e| {
                AdapterError::Malformed(format!("Invalid JSON in .gemini/settings.json: {}", e))
            })?;

            if let Some(mcp_servers_val) = parsed.get("mcpServers").and_then(|v| v.as_object()) {
                for (id, val) in mcp_servers_val {
                    let command = val
                        .get("command")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string();
                    let args: Vec<String> = val
                        .get("args")
                        .and_then(|v| v.as_array())
                        .map(|arr| {
                            arr.iter()
                                .map(|item| item.as_str().unwrap_or("").to_string())
                                .collect()
                        })
                        .unwrap_or_default();

                    let command_or_url = if args.is_empty() {
                        command
                    } else {
                        format!("{} {}", command, args.join(" "))
                    };

                    let mut env_placeholders = Vec::new();
                    if let Some(env_obj) = val.get("env").and_then(|v| v.as_object()) {
                        for key in env_obj.keys() {
                            env_placeholders.push(key.clone());
                        }
                    }
                    env_placeholders.sort();

                    mcp_servers.push(McpServer {
                        id: id.clone(),
                        transport: "stdio".to_string(),
                        command_or_url,
                        env_placeholders,
                        targets: vec!["gemini-cli".to_string()],
                        health: HealthStatus::Unknown,
                    });
                }
            }
        }

        Ok(ImportResult {
            skills,
            agents: Vec::new(),
            mcp_servers,
        })
    }

    fn project(
        &self,
        root: &Path,
        skills: &[Skill],
        _agents: &[Agent],
        mcp_servers: &[McpServer],
    ) -> Result<ProjectResult, AdapterError> {
        let mut written = Vec::new();

        let gemini_skills: Vec<&Skill> = skills
            .iter()
            .filter(|s| s.targets.contains(&"gemini-cli".to_string()))
            .collect();

        if !gemini_skills.is_empty() {
            let concatenated: String = gemini_skills
                .iter()
                .map(|s| s.source.as_str())
                .collect::<Vec<&str>>()
                .join("\n\n---\n\n");
            let output = format!(
                "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->\n{}",
                concatenated
            );
            fs::write(root.join("GEMINI.md"), output)
                .map_err(|e| AdapterError::Io(format!("Failed to write GEMINI.md: {}", e)))?;
            written.push("GEMINI.md".to_string());
        }

        let gemini_servers: Vec<&McpServer> = mcp_servers
            .iter()
            .filter(|s| s.targets.contains(&"gemini-cli".to_string()))
            .collect();

        if !gemini_servers.is_empty() {
            let settings_dir = root.join(".gemini");
            fs::create_dir_all(&settings_dir).map_err(|e| {
                AdapterError::Io(format!("Failed to create .gemini directory: {}", e))
            })?;
            let settings_path = settings_dir.join("settings.json");

            let mut current_json = if settings_path.exists() {
                let raw_json = fs::read_to_string(&settings_path).map_err(|e| {
                    AdapterError::Io(format!("Failed to read .gemini/settings.json: {}", e))
                })?;
                serde_json::from_str(&raw_json).map_err(|e| {
                    AdapterError::Malformed(format!("Invalid JSON in .gemini/settings.json: {}", e))
                })?
            } else {
                json!({})
            };

            if !current_json.is_object() {
                return Err(AdapterError::Malformed(
                    ".gemini/settings.json root is not an object".to_string(),
                ));
            }

            let mcp_servers_map = current_json
                .as_object_mut()
                .unwrap()
                .entry("mcpServers")
                .or_insert_with(|| json!({}))
                .as_object_mut()
                .ok_or_else(|| {
                    AdapterError::Malformed("mcpServers is not an object".to_string())
                })?;

            for server in gemini_servers {
                let parts: Vec<&str> = server.command_or_url.split_whitespace().collect();
                if parts.is_empty() {
                    continue;
                }
                let command = parts[0].to_string();
                let args: Vec<Value> = parts[1..]
                    .iter()
                    .map(|s| Value::String(s.to_string()))
                    .collect();

                let mut env_obj = serde_json::Map::new();
                if let Some(existing_server) = mcp_servers_map.get(&server.id) {
                    if let Some(existing_env) =
                        existing_server.get("env").and_then(|v| v.as_object())
                    {
                        env_obj = existing_env.clone();
                    }
                }

                for key in &server.env_placeholders {
                    if !env_obj.contains_key(key) {
                        env_obj.insert(key.clone(), Value::String("".to_string()));
                    }
                }

                let new_server = json!({
                    "command": command,
                    "args": args,
                    "env": env_obj
                });

                mcp_servers_map.insert(server.id.clone(), new_server);
            }

            let pretty = serde_json::to_string_pretty(&current_json)
                .map_err(|e| AdapterError::Malformed(format!("Failed to serialize JSON: {}", e)))?;
            fs::write(&settings_path, pretty).map_err(|e| {
                AdapterError::Io(format!("Failed to write .gemini/settings.json: {}", e))
            })?;
            written.push(".gemini/settings.json".to_string());
        }

        Ok(ProjectResult {
            written,
            symlinked: Vec::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_gemini_cli_detect() {
        let dir = tempdir().unwrap();
        let adapter = GeminiCliAdapter;
        assert!(!adapter.detect(dir.path()));

        fs::write(dir.path().join("GEMINI.md"), "test").unwrap();
        assert!(adapter.detect(dir.path()));

        let dir2 = tempdir().unwrap();
        fs::create_dir_all(dir2.path().join(".gemini")).unwrap();
        fs::write(dir2.path().join(".gemini/settings.json"), "{}").unwrap();
        assert!(adapter.detect(dir2.path()));
    }

    #[test]
    fn test_gemini_cli_import_export_roundtrip() {
        let dir = tempdir().unwrap();
        let adapter = GeminiCliAdapter;

        fs::write(dir.path().join("GEMINI.md"), "Project memory instructions").unwrap();
        fs::create_dir_all(dir.path().join(".gemini")).unwrap();
        fs::write(
            dir.path().join(".gemini/settings.json"),
            r#"{"theme": "dark", "mcpServers": {"filesystem": {"command": "npx", "args": ["-y", "@mcp/fs"], "env": {"ROOT": "/tmp"}}}}"#,
        ).unwrap();

        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills.len(), 1);
        assert_eq!(imported.skills[0].id, "gemini-cli-memory");
        assert_eq!(imported.skills[0].source, "Project memory instructions");

        assert_eq!(imported.mcp_servers.len(), 1);
        assert_eq!(imported.mcp_servers[0].id, "filesystem");
        assert_eq!(imported.mcp_servers[0].command_or_url, "npx -y @mcp/fs");
        assert_eq!(
            imported.mcp_servers[0].env_placeholders,
            vec!["ROOT".to_string()]
        );

        let out_dir = tempdir().unwrap();
        // Pre-existing unrelated settings must survive the merge.
        fs::create_dir_all(out_dir.path().join(".gemini")).unwrap();
        fs::write(
            out_dir.path().join(".gemini/settings.json"),
            r#"{"theme": "light"}"#,
        )
        .unwrap();

        let project_res = adapter
            .project(out_dir.path(), &imported.skills, &[], &imported.mcp_servers)
            .unwrap();

        assert_eq!(project_res.written.len(), 2);
        let projected_memory = fs::read_to_string(out_dir.path().join("GEMINI.md")).unwrap();
        assert!(projected_memory.contains("Project memory instructions"));

        let projected_settings =
            fs::read_to_string(out_dir.path().join(".gemini/settings.json")).unwrap();
        let parsed: Value = serde_json::from_str(&projected_settings).unwrap();
        assert_eq!(parsed["theme"], "light");
        assert_eq!(parsed["mcpServers"]["filesystem"]["command"], "npx");
    }

    #[test]
    fn test_gemini_cli_stress_malformed_json() {
        let dir = tempdir().unwrap();
        let adapter = GeminiCliAdapter;
        fs::create_dir_all(dir.path().join(".gemini")).unwrap();
        fs::write(dir.path().join(".gemini/settings.json"), "{ not json").unwrap();
        let res = adapter.import(dir.path());
        assert!(matches!(res, Err(AdapterError::Malformed(_))));
    }

    #[test]
    fn test_gemini_cli_stress_project_non_object_settings() {
        let dir = tempdir().unwrap();
        let adapter = GeminiCliAdapter;
        fs::create_dir_all(dir.path().join(".gemini")).unwrap();
        fs::write(dir.path().join(".gemini/settings.json"), "[1, 2, 3]").unwrap();

        let server = McpServer {
            id: "srv".to_string(),
            transport: "stdio".to_string(),
            command_or_url: "node".to_string(),
            env_placeholders: vec![],
            targets: vec!["gemini-cli".to_string()],
            health: HealthStatus::Unknown,
        };

        let res = adapter.project(dir.path(), &[], &[], &[server]);
        assert!(matches!(res, Err(AdapterError::Malformed(_))));
    }
}
