use crate::adapter::{Adapter, AdapterError};
use sha2::{Digest, Sha256};
use std::path::{Component, Path, PathBuf};

pub mod agy_cli;
pub mod aider;
pub mod claude_code;
pub mod cline;
pub mod continue_adapter;
pub mod cursor;
pub mod gemini_cli;
pub mod github_copilot;
pub mod openai_codex;
pub mod opencode;
pub mod roo_code;
pub mod windsurf;
pub mod zed;

/// Returns all 13 implemented adapters.
pub fn all_adapters() -> Vec<Box<dyn Adapter>> {
    vec![
        Box::new(agy_cli::AgyCliAdapter),
        Box::new(cline::ClineAdapter),
        Box::new(opencode::OpenCodeAdapter),
        Box::new(github_copilot::GitHubCopilotAdapter),
        Box::new(windsurf::WindsurfAdapter),
        Box::new(gemini_cli::GeminiCliAdapter),
        Box::new(zed::ZedAdapter),
        Box::new(aider::AiderAdapter),
        Box::new(roo_code::RooCodeAdapter),
        Box::new(cursor::CursorAdapter),
        Box::new(continue_adapter::ContinueAdapter),
        Box::new(claude_code::ClaudeCodeAdapter),
        Box::new(openai_codex::OpenAiCodexAdapter),
    ]
}

use std::fs;

/// Helper to compute SHA256 of string content.
pub fn compute_sha256(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    hex::encode(hasher.finalize())
}

/// Helper to write file contents only if they have changed, preserving mtime on idempotent writes.
pub fn write_if_changed(path: &Path, content: impl AsRef<[u8]>) -> std::io::Result<bool> {
    if path.exists() {
        if let Ok(existing) = fs::read(path) {
            if existing == content.as_ref() {
                return Ok(false);
            }
        }
    }
    fs::write(path, content)?;
    Ok(true)
}

/// Helper to strip the LLM Neurosurgeon provenance header from imported rules.
pub fn strip_provenance(content: &str) -> String {
    let normalized = content.replace("\r\n", "\n");
    let header = "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->";
    let trimmed = normalized.trim_start();
    if let Some(rest) = trimmed.strip_prefix(header) {
        rest.trim_start().to_string()
    } else {
        normalized
    }
}

/// Preprocesses JSONC (JSON with comments and trailing commas) into standard JSON.
pub fn clean_jsonc(input: &str) -> String {
    let mut output = String::new();
    let mut in_string = false;
    let mut escape = false;
    let chars: Vec<char> = input.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if in_string {
            output.push(c);
            if escape {
                escape = false;
            } else if c == '\\' {
                escape = true;
            } else if c == '"' {
                in_string = false;
            }
            i += 1;
        } else {
            if c == '"' {
                in_string = true;
                output.push(c);
                i += 1;
            } else if c == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
                i += 2;
                while i < chars.len() && chars[i] != '\n' {
                    i += 1;
                }
            } else if c == '/' && i + 1 < chars.len() && chars[i + 1] == '*' {
                i += 2;
                while i + 1 < chars.len() && !(chars[i] == '*' && chars[i + 1] == '/') {
                    i += 1;
                }
                i += 2; // skip */
            } else {
                output.push(c);
                i += 1;
            }
        }
    }

    // Strip trailing commas before } or ]
    let clean_chars: Vec<char> = output.chars().collect();
    let mut final_output = String::new();
    let mut j = 0;
    while j < clean_chars.len() {
        if clean_chars[j] == ',' {
            let mut k = j + 1;
            while k < clean_chars.len() && clean_chars[k].is_whitespace() {
                k += 1;
            }
            if k < clean_chars.len() && (clean_chars[k] == '}' || clean_chars[k] == ']') {
                j += 1;
                continue;
            }
        }
        final_output.push(clean_chars[j]);
        j += 1;
    }

    final_output
}

/// Helper to get the home directory.
pub fn get_home_dir() -> Option<PathBuf> {
    std::env::var("HOME")
        .ok()
        .or_else(|| std::env::var("USERPROFILE").ok())
        .map(PathBuf::from)
}

/// Splits a `---`-delimited frontmatter block from the body that follows,
/// shared by the `.mdc`-style rule formats (cursor, continue).
pub fn split_frontmatter(content: &str) -> (Option<String>, String) {
    let lines: Vec<&str> = content.lines().collect();
    if lines.first().map(|l| l.trim()) == Some("---") {
        if let Some(rel_end) = lines.iter().skip(1).position(|l| l.trim() == "---") {
            let end = rel_end + 1;
            let fm = lines[1..end].join("\n");
            let body = lines[end + 1..].join("\n");
            return (Some(fm), body);
        }
    }
    (None, content.to_string())
}

/// The `description` / `globs` / `alwaysApply` frontmatter fields shared by
/// Cursor's `.mdc` rule files and Continue's `.continue/rules/*.md` files.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MdcFrontmatter {
    pub globs: Vec<String>,
    pub always_apply: bool,
}

pub fn parse_mdc_frontmatter(fm: &str) -> Result<MdcFrontmatter, AdapterError> {
    let mut result = MdcFrontmatter::default();
    let mut has_recognized_key = false;
    for line in fm.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some(colon_idx) = line.find(':') else {
            continue;
        };
        let key = line[..colon_idx].trim();
        let val = line[colon_idx + 1..].trim();
        if !key.is_empty() {
            has_recognized_key = true;
        }
        match key {
            "description" => {
                has_recognized_key = true;
            }
            "globs" => {
                has_recognized_key = true;
                if val.starts_with('[') && val.ends_with(']') {
                    result.globs = val[1..val.len() - 1]
                        .split(',')
                        .map(|s| s.trim().trim_matches('"').trim_matches('\'').to_string())
                        .filter(|s| !s.is_empty())
                        .collect();
                } else if !val.is_empty() {
                    result.globs = vec![val.trim_matches('"').trim_matches('\'').to_string()];
                }
                for g in &result.globs {
                    if has_path_traversal(g) {
                        return Err(AdapterError::Malformed(format!(
                            "Path traversal in rule globs: {g}"
                        )));
                    }
                }
            }
            "alwaysApply" | "always_apply" => {
                has_recognized_key = true;
                result.always_apply = val == "true";
            }
            _ => {}
        }
    }
    if !has_recognized_key && !fm.trim().is_empty() {
        return Err(AdapterError::Malformed(
            "Frontmatter is missing required keys (description, globs, or alwaysApply)".to_string(),
        ));
    }
    Ok(result)
}

pub fn serialize_mdc_frontmatter(fm: &MdcFrontmatter) -> String {
    let globs_str = fm
        .globs
        .iter()
        .map(|g| format!("\"{}\"", g))
        .collect::<Vec<String>>()
        .join(", ");
    format!(
        "---\ndescription: \nglobs: [{}]\nalwaysApply: {}\n---",
        globs_str, fm.always_apply
    )
}

/// Helper to detect if a path string or command contains path traversal (`..` or escaping directory).
pub fn has_path_traversal(s: &str) -> bool {
    let trimmed = s.trim();
    if trimmed.is_empty() {
        return false;
    }
    if trimmed.contains("../")
        || trimmed.contains("..\\")
        || trimmed == ".."
        || trimmed.ends_with("/..")
        || trimmed.ends_with("\\..")
        || trimmed.contains("/../")
        || trimmed.contains("\\..\\")
    {
        return true;
    }
    for component in Path::new(trimmed).components() {
        if matches!(component, Component::ParentDir) {
            return true;
        }
    }
    false
}

/// Helper to parse and validate an MCP server entry from JSON.
/// Returns Malformed error if missing command/url or if command/args has path traversal.
pub fn parse_and_validate_mcp_server(
    id: &str,
    val: &serde_json::Value,
    target_adapter: &str,
    out_servers: &mut Vec<crate::model::McpServer>,
) -> Result<(), AdapterError> {
    let Some(obj) = val.as_object() else {
        return Err(AdapterError::Malformed(format!(
            "MCP server '{id}' is not an object"
        )));
    };

    let url_opt = obj.get("url").and_then(|v| v.as_str());
    let command_opt = obj.get("command").and_then(|v| v.as_str());

    let (transport, command_or_url) = if let Some(url) = url_opt {
        if url.trim().is_empty() {
            return Err(AdapterError::Malformed(format!(
                "MCP server '{id}' has empty url"
            )));
        }
        if has_path_traversal(url) {
            return Err(AdapterError::Malformed(format!(
                "Path traversal in MCP server '{id}' url: {url}"
            )));
        }
        ("http".to_string(), url.to_string())
    } else if let Some(command) = command_opt {
        if command.trim().is_empty() {
            return Err(AdapterError::Malformed(format!(
                "MCP server '{id}' has empty command"
            )));
        }
        if has_path_traversal(command) {
            return Err(AdapterError::Malformed(format!(
                "Path traversal in MCP server '{id}' command: {command}"
            )));
        }

        let args: Vec<String> = obj
            .get("args")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .map(|item| item.as_str().unwrap_or("").to_string())
                    .collect()
            })
            .unwrap_or_default();

        for arg in &args {
            if has_path_traversal(arg) {
                return Err(AdapterError::Malformed(format!(
                    "Path traversal in MCP server '{id}' arg: {arg}"
                )));
            }
        }

        let full = if args.is_empty() {
            command.to_string()
        } else {
            format!("{} {}", command, args.join(" "))
        };
        ("stdio".to_string(), full)
    } else {
        return Err(AdapterError::Malformed(format!(
            "MCP server '{id}' is missing required `command` or `url`"
        )));
    };

    let mut env_placeholders = Vec::new();
    if let Some(env_obj) = obj.get("env").and_then(|v| v.as_object()) {
        for key in env_obj.keys() {
            env_placeholders.push(key.clone());
        }
    }
    env_placeholders.sort();

    out_servers.push(crate::model::McpServer {
        id: id.to_string(),
        transport,
        command_or_url,
        env_placeholders,
        targets: vec![target_adapter.to_string()],
        health: crate::model::HealthStatus::Unknown,
    });

    Ok(())
}

/// Helper to get the Windsurf mcp.json path.
pub fn get_windsurf_mcp_path() -> Option<PathBuf> {
    let home = get_home_dir()?;
    let devin_path = home.join(".devin/mcp.json");
    if devin_path.exists() {
        return Some(devin_path);
    }
    let codeium_path = home.join(".codeium/windsurf/mcp.json");
    if codeium_path.exists() {
        return Some(codeium_path);
    }
    Some(codeium_path)
}

/// Joins `relative` onto `root`, refusing any path that would escape
/// `root`. Use this whenever a projected file's path is built from data
/// that ultimately came from another tool's config during `import()`
/// (a skill id, an agent slug, a trigger/glob) rather than a fixed
/// literal — that data is attacker-influenced (a malicious or malformed
/// upstream config), so a `..` component or an absolute path in it must
/// not be allowed to write outside the tool root being projected to.
pub fn safe_join(root: &Path, relative: &str) -> Result<PathBuf, AdapterError> {
    let candidate = Path::new(relative);
    for component in candidate.components() {
        match component {
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => {
                return Err(AdapterError::Malformed(format!(
                    "refusing to write outside the target root: {relative}"
                )));
            }
            Component::CurDir | Component::Normal(_) => {}
        }
    }
    Ok(root.join(candidate))
}

#[cfg(test)]
mod registry_tests {
    use super::*;
    use crate::test_home::HomeGuard;
    use tempfile::tempdir;

    #[test]
    fn all_13_adapters_registered_with_unique_ids() {
        let adapters = all_adapters();
        assert_eq!(adapters.len(), 13);

        let mut ids: Vec<&str> = adapters.iter().map(|a| a.id()).collect();
        let before = ids.len();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), before, "duplicate adapter ids: {:?}", ids);
    }

    #[test]
    fn no_adapter_detects_an_empty_root() {
        let dir = tempdir().unwrap();
        // Several adapters (zed, openai-codex, windsurf) also consult
        // $HOME, where a user-level install counts as present. Pin HOME to
        // an empty temp dir so this asserts the adapters read the scanned
        // root correctly, not whether the machine running the suite happens
        // to have one of these tools installed.
        let home = tempdir().unwrap();
        let _home = HomeGuard::set(home.path());
        for adapter in all_adapters() {
            assert!(
                !adapter.detect(dir.path()),
                "{} falsely detected an empty root",
                adapter.id()
            );
        }
    }
}

#[cfg(test)]
mod safe_join_tests {
    use super::*;

    #[test]
    fn joins_a_plain_relative_path() {
        let root = Path::new("/brain/out");
        let result = safe_join(root, ".cursor/rules/repo-conventions.mdc").unwrap();
        assert_eq!(
            result,
            Path::new("/brain/out/.cursor/rules/repo-conventions.mdc")
        );
    }

    #[test]
    fn rejects_parent_dir_traversal() {
        let root = Path::new("/brain/out");
        assert!(matches!(
            safe_join(root, "../traversal_output/evil.md"),
            Err(AdapterError::Malformed(_))
        ));
    }

    #[test]
    fn rejects_parent_dir_traversal_nested_inside_a_normal_prefix() {
        let root = Path::new("/brain/out");
        assert!(matches!(
            safe_join(root, "src/../../evil.md"),
            Err(AdapterError::Malformed(_))
        ));
    }

    #[test]
    fn rejects_absolute_paths() {
        let root = Path::new("/brain/out");
        assert!(matches!(
            safe_join(root, "/etc/cron.d/evil"),
            Err(AdapterError::Malformed(_))
        ));
    }
}
