use crate::adapter::{Adapter, AdapterError};
use sha2::{Digest, Sha256};
use std::path::{Component, Path, PathBuf};

pub mod aider;
pub mod claude_code;
pub mod cline;
pub mod continue_adapter;
pub mod cursor;
pub mod gemini_cli;
pub mod github_copilot;
pub mod openai_codex;
pub mod opencode;
pub mod roo_code;
pub mod windsurf;
pub mod zed;

/// Returns all 12 implemented adapters (Phase 3 Milestones 1-3).
pub fn all_adapters() -> Vec<Box<dyn Adapter>> {
    vec![
        Box::new(cline::ClineAdapter),
        Box::new(opencode::OpenCodeAdapter),
        Box::new(github_copilot::GitHubCopilotAdapter),
        Box::new(windsurf::WindsurfAdapter),
        Box::new(gemini_cli::GeminiCliAdapter),
        Box::new(zed::ZedAdapter),
        Box::new(aider::AiderAdapter),
        Box::new(roo_code::RooCodeAdapter),
        Box::new(cursor::CursorAdapter),
        Box::new(continue_adapter::ContinueAdapter),
        Box::new(claude_code::ClaudeCodeAdapter),
        Box::new(openai_codex::OpenAiCodexAdapter),
    ]
}

/// Helper to compute SHA256 of string content.
pub fn compute_sha256(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    hex::encode(hasher.finalize())
}

/// Helper to strip the LLM Neurosurgeon provenance header from imported rules.
pub fn strip_provenance(content: &str) -> String {
    let header = "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->";
    let trimmed = content.trim_start();
    if trimmed.starts_with(header) {
        trimmed[header.len()..].trim_start().to_string()
    } else {
        content.to_string()
    }
}

/// Preprocesses JSONC (JSON with comments and trailing commas) into standard JSON.
pub fn clean_jsonc(input: &str) -> String {
    let mut output = String::new();
    let mut in_string = false;
    let mut escape = false;
    let chars: Vec<char> = input.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if in_string {
            output.push(c);
            if escape {
                escape = false;
            } else if c == '\\' {
                escape = true;
            } else if c == '"' {
                in_string = false;
            }
            i += 1;
        } else {
            if c == '"' {
                in_string = true;
                output.push(c);
                i += 1;
            } else if c == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
                i += 2;
                while i < chars.len() && chars[i] != '\n' {
                    i += 1;
                }
            } else if c == '/' && i + 1 < chars.len() && chars[i + 1] == '*' {
                i += 2;
                while i + 1 < chars.len() && !(chars[i] == '*' && chars[i + 1] == '/') {
                    i += 1;
                }
                i += 2; // skip */
            } else {
                output.push(c);
                i += 1;
            }
        }
    }

    // Strip trailing commas before } or ]
    let clean_chars: Vec<char> = output.chars().collect();
    let mut final_output = String::new();
    let mut j = 0;
    while j < clean_chars.len() {
        if clean_chars[j] == ',' {
            let mut k = j + 1;
            while k < clean_chars.len() && clean_chars[k].is_whitespace() {
                k += 1;
            }
            if k < clean_chars.len() && (clean_chars[k] == '}' || clean_chars[k] == ']') {
                j += 1;
                continue;
            }
        }
        final_output.push(clean_chars[j]);
        j += 1;
    }

    final_output
}

/// Helper to get the home directory.
pub fn get_home_dir() -> Option<PathBuf> {
    std::env::var("HOME")
        .ok()
        .or_else(|| std::env::var("USERPROFILE").ok())
        .map(PathBuf::from)
}

/// Splits a `---`-delimited frontmatter block from the body that follows,
/// shared by the `.mdc`-style rule formats (cursor, continue).
pub fn split_frontmatter(content: &str) -> (Option<String>, String) {
    let lines: Vec<&str> = content.lines().collect();
    if lines.first().map(|l| l.trim()) == Some("---") {
        if let Some(rel_end) = lines.iter().skip(1).position(|l| l.trim() == "---") {
            let end = rel_end + 1;
            let fm = lines[1..end].join("\n");
            let body = lines[end + 1..].join("\n");
            return (Some(fm), body);
        }
    }
    (None, content.to_string())
}

/// The `description` / `globs` / `alwaysApply` frontmatter fields shared by
/// Cursor's `.mdc` rule files and Continue's `.continue/rules/*.md` files.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MdcFrontmatter {
    pub globs: Vec<String>,
    pub always_apply: bool,
}

pub fn parse_mdc_frontmatter(fm: &str) -> MdcFrontmatter {
    let mut result = MdcFrontmatter::default();
    for line in fm.lines() {
        let line = line.trim();
        let Some(colon_idx) = line.find(':') else {
            continue;
        };
        let key = line[..colon_idx].trim();
        let val = line[colon_idx + 1..].trim();
        match key {
            "globs" => {
                if val.starts_with('[') && val.ends_with(']') {
                    result.globs = val[1..val.len() - 1]
                        .split(',')
                        .map(|s| s.trim().trim_matches('"').trim_matches('\'').to_string())
                        .filter(|s| !s.is_empty())
                        .collect();
                } else if !val.is_empty() {
                    result.globs = vec![val.trim_matches('"').trim_matches('\'').to_string()];
                }
            }
            "alwaysApply" => {
                result.always_apply = val == "true";
            }
            _ => {}
        }
    }
    result
}

pub fn serialize_mdc_frontmatter(fm: &MdcFrontmatter) -> String {
    let globs_str = fm
        .globs
        .iter()
        .map(|g| format!("\"{}\"", g))
        .collect::<Vec<String>>()
        .join(", ");
    format!(
        "---\ndescription: \nglobs: [{}]\nalwaysApply: {}\n---",
        globs_str, fm.always_apply
    )
}

/// Helper to get the Windsurf mcp.json path.
pub fn get_windsurf_mcp_path() -> Option<PathBuf> {
    let home = get_home_dir()?;
    let devin_path = home.join(".devin/mcp.json");
    if devin_path.exists() {
        return Some(devin_path);
    }
    let codeium_path = home.join(".codeium/windsurf/mcp.json");
    if codeium_path.exists() {
        return Some(codeium_path);
    }
    Some(codeium_path)
}

/// Joins `relative` onto `root`, refusing any path that would escape
/// `root`. Use this whenever a projected file's path is built from data
/// that ultimately came from another tool's config during `import()`
/// (a skill id, an agent slug, a trigger/glob) rather than a fixed
/// literal — that data is attacker-influenced (a malicious or malformed
/// upstream config), so a `..` component or an absolute path in it must
/// not be allowed to write outside the tool root being projected to.
pub fn safe_join(root: &Path, relative: &str) -> Result<PathBuf, AdapterError> {
    let candidate = Path::new(relative);
    for component in candidate.components() {
        match component {
            Component::ParentDir | Component::RootDir | Component::Prefix(_) => {
                return Err(AdapterError::Malformed(format!(
                    "refusing to write outside the target root: {relative}"
                )));
            }
            Component::CurDir | Component::Normal(_) => {}
        }
    }
    Ok(root.join(candidate))
}

#[cfg(test)]
mod registry_tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn all_12_adapters_registered_with_unique_ids() {
        let adapters = all_adapters();
        assert_eq!(adapters.len(), 12);

        let mut ids: Vec<&str> = adapters.iter().map(|a| a.id()).collect();
        let before = ids.len();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), before, "duplicate adapter ids: {:?}", ids);
    }

    #[test]
    fn no_adapter_detects_an_empty_root() {
        let dir = tempdir().unwrap();
        for adapter in all_adapters() {
            assert!(
                !adapter.detect(dir.path()),
                "{} falsely detected an empty root",
                adapter.id()
            );
        }
    }
}

#[cfg(test)]
mod safe_join_tests {
    use super::*;

    #[test]
    fn joins_a_plain_relative_path() {
        let root = Path::new("/brain/out");
        let result = safe_join(root, ".cursor/rules/repo-conventions.mdc").unwrap();
        assert_eq!(
            result,
            Path::new("/brain/out/.cursor/rules/repo-conventions.mdc")
        );
    }

    #[test]
    fn rejects_parent_dir_traversal() {
        let root = Path::new("/brain/out");
        assert!(matches!(
            safe_join(root, "../traversal_output/evil.md"),
            Err(AdapterError::Malformed(_))
        ));
    }

    #[test]
    fn rejects_parent_dir_traversal_nested_inside_a_normal_prefix() {
        let root = Path::new("/brain/out");
        assert!(matches!(
            safe_join(root, "src/../../evil.md"),
            Err(AdapterError::Malformed(_))
        ));
    }

    #[test]
    fn rejects_absolute_paths() {
        let root = Path::new("/brain/out");
        assert!(matches!(
            safe_join(root, "/etc/cron.d/evil"),
            Err(AdapterError::Malformed(_))
        ));
    }
}
