use std::path::PathBuf;
use sha2::{Sha256, Digest};
use crate::adapter::Adapter;

pub mod cline;
pub mod opencode;
pub mod github_copilot;
pub mod windsurf;

/// Returns all implemented Phase 3 Milestone 1 adapters.
pub fn all_adapters() -> Vec<Box<dyn Adapter>> {
    vec![
        Box::new(cline::ClineAdapter),
        Box::new(opencode::OpenCodeAdapter),
        Box::new(github_copilot::GitHubCopilotAdapter),
        Box::new(windsurf::WindsurfAdapter),
    ]
}

/// Helper to compute SHA256 of string content.
pub fn compute_sha256(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    hex::encode(hasher.finalize())
}

/// Helper to strip the LLM Neurosurgeon provenance header from imported rules.
pub fn strip_provenance(content: &str) -> String {
    let header = "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->";
    let trimmed = content.trim_start();
    if trimmed.starts_with(header) {
        trimmed[header.len()..].trim_start().to_string()
    } else {
        content.to_string()
    }
}

/// Preprocesses JSONC (JSON with comments and trailing commas) into standard JSON.
pub fn clean_jsonc(input: &str) -> String {
    let mut output = String::new();
    let mut in_string = false;
    let mut escape = false;
    let chars: Vec<char> = input.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if in_string {
            output.push(c);
            if escape {
                escape = false;
            } else if c == '\\' {
                escape = true;
            } else if c == '"' {
                in_string = false;
            }
            i += 1;
        } else {
            if c == '"' {
                in_string = true;
                output.push(c);
                i += 1;
            } else if c == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
                i += 2;
                while i < chars.len() && chars[i] != '\n' {
                    i += 1;
                }
            } else if c == '/' && i + 1 < chars.len() && chars[i + 1] == '*' {
                i += 2;
                while i + 1 < chars.len() && !(chars[i] == '*' && chars[i + 1] == '/') {
                    i += 1;
                }
                i += 2; // skip */
            } else {
                output.push(c);
                i += 1;
            }
        }
    }

    // Strip trailing commas before } or ]
    let clean_chars: Vec<char> = output.chars().collect();
    let mut final_output = String::new();
    let mut j = 0;
    while j < clean_chars.len() {
        if clean_chars[j] == ',' {
            let mut k = j + 1;
            while k < clean_chars.len() && clean_chars[k].is_whitespace() {
                k += 1;
            }
            if k < clean_chars.len() && (clean_chars[k] == '}' || clean_chars[k] == ']') {
                j += 1;
                continue;
            }
        }
        final_output.push(clean_chars[j]);
        j += 1;
    }

    final_output
}

/// Helper to get the home directory.
pub fn get_home_dir() -> Option<PathBuf> {
    std::env::var("HOME")
        .ok()
        .or_else(|| std::env::var("USERPROFILE").ok())
        .map(PathBuf::from)
}

/// Helper to get the Windsurf mcp.json path.
pub fn get_windsurf_mcp_path() -> Option<PathBuf> {
    let home = get_home_dir()?;
    let devin_path = home.join(".devin/mcp.json");
    if devin_path.exists() {
        return Some(devin_path);
    }
    let codeium_path = home.join(".codeium/windsurf/mcp.json");
    if codeium_path.exists() {
        return Some(codeium_path);
    }
    Some(codeium_path)
}
