use super::{clean_jsonc, compute_sha256, get_windsurf_mcp_path, strip_provenance};
use crate::adapter::{Adapter, AdapterError, ImportResult, ProjectResult};
use crate::model::{Agent, HealthStatus, McpServer, Skill};
use serde_json::{json, Value};
use std::fs;
use std::path::Path;

pub struct WindsurfAdapter;

impl Adapter for WindsurfAdapter {
    fn id(&self) -> &'static str {
        "windsurf"
    }

    fn detect(&self, root: &Path) -> bool {
        root.join(".windsurfrules").exists()
    }

    fn import(&self, root: &Path) -> Result<ImportResult, AdapterError> {
        let mut skills = Vec::new();
        let mut mcp_servers = Vec::new();

        let rules_path = root.join(".windsurfrules");
        if rules_path.exists() {
            let raw = fs::read_to_string(&rules_path)
                .map_err(|e| AdapterError::Io(format!("Failed to read .windsurfrules: {}", e)))?;
            let content = strip_provenance(&raw);
            let sha256 = compute_sha256(&content);
            skills.push(Skill {
                id: "windsurf-rules".to_string(),
                version: "1.0.0".to_string(),
                triggers: vec!["*".to_string()],
                targets: vec!["windsurf".to_string()],
                source: content,
                sha256,
            });
        }

        if let Some(mcp_path) = get_windsurf_mcp_path() {
            if mcp_path.exists() {
                let raw_json = fs::read_to_string(&mcp_path).map_err(|e| {
                    AdapterError::Io(format!("Failed to read Windsurf mcp.json: {}", e))
                })?;
                let cleaned = clean_jsonc(&raw_json);
                let parsed: Value = serde_json::from_str(&cleaned).map_err(|e| {
                    AdapterError::Malformed(format!("Invalid JSON in Windsurf mcp.json: {}", e))
                })?;

                if let Some(mcp_servers_val) = parsed.get("mcpServers").and_then(|v| v.as_object())
                {
                    for (id, val) in mcp_servers_val {
                        let command = val
                            .get("command")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string();
                        let args: Vec<String> = val
                            .get("args")
                            .and_then(|v| v.as_array())
                            .map(|arr| {
                                arr.iter()
                                    .map(|item| item.as_str().unwrap_or("").to_string())
                                    .collect()
                            })
                            .unwrap_or_default();

                        let command_or_url = if args.is_empty() {
                            command
                        } else {
                            format!("{} {}", command, args.join(" "))
                        };

                        let mut env_placeholders = Vec::new();
                        if let Some(env_obj) = val.get("env").and_then(|v| v.as_object()) {
                            for key in env_obj.keys() {
                                env_placeholders.push(key.clone());
                            }
                        }
                        env_placeholders.sort();

                        mcp_servers.push(McpServer {
                            id: id.clone(),
                            transport: "stdio".to_string(),
                            command_or_url,
                            env_placeholders,
                            targets: vec!["windsurf".to_string()],
                            health: HealthStatus::Unknown,
                        });
                    }
                }
            }
        }

        Ok(ImportResult {
            skills,
            agents: Vec::new(),
            mcp_servers,
        })
    }

    fn project(
        &self,
        root: &Path,
        skills: &[Skill],
        _agents: &[Agent],
        mcp_servers: &[McpServer],
    ) -> Result<ProjectResult, AdapterError> {
        let mut written = Vec::new();

        let windsurf_skills: Vec<&Skill> = skills
            .iter()
            .filter(|s| s.targets.contains(&"windsurf".to_string()))
            .collect();

        if !windsurf_skills.is_empty() {
            let concatenated: String = windsurf_skills
                .iter()
                .map(|s| s.source.as_str())
                .collect::<Vec<&str>>()
                .join("\n\n---\n\n");
            let output = format!(
                "<!-- GENERATED BY LLM NEUROSURGEON — edit in the Brain -->\n{}",
                concatenated
            );
            fs::write(root.join(".windsurfrules"), output)
                .map_err(|e| AdapterError::Io(format!("Failed to write .windsurfrules: {}", e)))?;
            written.push(".windsurfrules".to_string());
        }

        let windsurf_servers: Vec<&McpServer> = mcp_servers
            .iter()
            .filter(|s| s.targets.contains(&"windsurf".to_string()))
            .collect();

        if !windsurf_servers.is_empty() {
            if let Some(mcp_path) = get_windsurf_mcp_path() {
                if let Some(parent) = mcp_path.parent() {
                    fs::create_dir_all(parent).map_err(|e| {
                        AdapterError::Io(format!(
                            "Failed to create Windsurf config directory: {}",
                            e
                        ))
                    })?;
                }

                let mut current_json = if mcp_path.exists() {
                    let raw_json = fs::read_to_string(&mcp_path).map_err(|e| {
                        AdapterError::Io(format!("Failed to read Windsurf mcp.json: {}", e))
                    })?;
                    let cleaned = clean_jsonc(&raw_json);
                    serde_json::from_str(&cleaned).unwrap_or_else(|_| json!({ "mcpServers": {} }))
                } else {
                    json!({ "mcpServers": {} })
                };

                if !current_json.is_object() {
                    current_json = json!({ "mcpServers": {} });
                }

                let mcp_servers_map = current_json
                    .as_object_mut()
                    .unwrap()
                    .entry("mcpServers")
                    .or_insert_with(|| json!({}))
                    .as_object_mut()
                    .ok_or_else(|| {
                        AdapterError::Malformed("mcpServers is not an object".to_string())
                    })?;

                for server in windsurf_servers {
                    let parts: Vec<&str> = server.command_or_url.split_whitespace().collect();
                    if parts.is_empty() {
                        continue;
                    }
                    let command = parts[0].to_string();
                    let args: Vec<Value> = parts[1..]
                        .iter()
                        .map(|s| Value::String(s.to_string()))
                        .collect();

                    let mut env_obj = serde_json::Map::new();
                    if let Some(existing_server) = mcp_servers_map.get(&server.id) {
                        if let Some(existing_env) =
                            existing_server.get("env").and_then(|v| v.as_object())
                        {
                            env_obj = existing_env.clone();
                        }
                    }

                    for key in &server.env_placeholders {
                        if !env_obj.contains_key(key) {
                            env_obj.insert(key.clone(), Value::String("".to_string()));
                        }
                    }

                    let new_server = json!({
                        "command": command,
                        "args": args,
                        "env": env_obj
                    });

                    mcp_servers_map.insert(server.id.clone(), new_server);
                }

                let pretty = serde_json::to_string_pretty(&current_json).map_err(|e| {
                    AdapterError::Malformed(format!("Failed to serialize JSON: {}", e))
                })?;
                fs::write(&mcp_path, pretty).map_err(|e| {
                    AdapterError::Io(format!("Failed to write Windsurf mcp.json: {}", e))
                })?;

                written.push(mcp_path.to_string_lossy().into_owned());
            }
        }

        Ok(ProjectResult {
            written,
            symlinked: Vec::new(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_windsurf_detect() {
        let dir = tempdir().unwrap();
        let adapter = WindsurfAdapter;
        assert!(!adapter.detect(dir.path()));

        fs::write(dir.path().join(".windsurfrules"), "test").unwrap();
        assert!(adapter.detect(dir.path()));
    }

    #[test]
    fn test_windsurf_import_export_roundtrip() {
        let dir = tempdir().unwrap();
        let adapter = WindsurfAdapter;

        // Set custom HOME environment variable for the test to point to a temp dir
        let home_dir = tempdir().unwrap();
        std::env::set_var("HOME", home_dir.path());

        fs::write(
            dir.path().join(".windsurfrules"),
            "windsurf global instructions",
        )
        .unwrap();

        let mcp_dir = home_dir.path().join(".devin");
        fs::create_dir_all(&mcp_dir).unwrap();
        fs::write(
            mcp_dir.join("mcp.json"),
            r#"{"mcpServers": {"wind-mcp": {"command": "python", "args": ["main.py"]}}}"#,
        )
        .unwrap();

        let imported = adapter.import(dir.path()).unwrap();
        assert_eq!(imported.skills.len(), 1);
        assert_eq!(imported.skills[0].id, "windsurf-rules");
        assert_eq!(imported.skills[0].source, "windsurf global instructions");

        assert_eq!(imported.mcp_servers.len(), 1);
        assert_eq!(imported.mcp_servers[0].id, "wind-mcp");
        assert_eq!(imported.mcp_servers[0].command_or_url, "python main.py");

        // Project back
        let out_dir = tempdir().unwrap();
        let out_home = tempdir().unwrap();
        std::env::set_var("HOME", out_home.path());

        let project_res = adapter
            .project(out_dir.path(), &imported.skills, &[], &imported.mcp_servers)
            .unwrap();

        assert_eq!(project_res.written.len(), 2);
        assert!(project_res.written.contains(&".windsurfrules".to_string()));

        let projected_rules = fs::read_to_string(out_dir.path().join(".windsurfrules")).unwrap();
        assert!(projected_rules.contains("windsurf global instructions"));
    }
}
